"use client";
import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { SearchableDropdown, type DropdownOption } from "../Dropdown";
import styles from "./UsersTree.module.css";

type Location = { LocationId: string; ParentId: string | null; LocationName: string; LocationType: string };
type User = { UserId: string; PersonId: string; LocationId: string; CodeMelli: string; FirstName: string; LastName: string; TelHamrah: string | null; OnvanPost: string; IsActive: boolean; HasPhoto: boolean };
type IconKind = "chevron" | "building" | "map" | "user" | "search" | "plus" | "key" | "trash" | "close" | "copy" | "check";

function Icon({ kind }: { kind: IconKind }) {
  const paths: Record<IconKind, ReactNode> = {
    chevron:<path d="m9 18 6-6-6-6"/>, building:<path d="M4 21V4h12v17M16 9h4v12M8 8h4M8 12h4M8 16h4M2 21h20"/>,
    map:<><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3Z"/><path d="M9 3v15M15 6v15"/></>, user:<><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></>,
    search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, plus:<path d="M12 5v14M5 12h14"/>, key:<><circle cx="8" cy="15" r="4"/><path d="m11 12 8-8M15 8l3 3M17 6l2 2"/></>, trash:<><path d="M4 7h16M9 3h6l1 4H8M6 7l1 14h10l1-14"/></>, close:<path d="m6 6 12 12M18 6 6 18"/>, copy:<><rect x="9" y="9" width="11" height="11" rx="2"/><path d="M15 9V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2h3"/></>, check:<path d="m5 12 4 4L19 6"/>,
  };
  return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[kind]}</svg>;
}

async function apiMessage(response: Response) { try { return ((await response.json()) as { message?: string }).message || "عملیات انجام نشد."; } catch { return "عملیات انجام نشد."; } }
function latinDigits(value:string){return value.replace(/[۰-۹]/g,digit=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(digit))).replace(/[٠-٩]/g,digit=>String("٠١٢٣٤٥٦٧٨٩".indexOf(digit)));}

export default function UsersTree() {
  const [locations,setLocations]=useState<Location[]>([]), [users,setUsers]=useState<User[]>([]);
  const [expanded,setExpanded]=useState<Set<string>>(new Set(["1"]));
  const [loaded,setLoaded]=useState<Set<string>>(new Set()), [loadingNodes,setLoadingNodes]=useState<Set<string>>(new Set());
  const [totalUsers,setTotalUsers]=useState(0);
  const [search,setSearch]=useState(""), [error,setError]=useState(""), [formError,setFormError]=useState("");
  const [loading,setLoading]=useState(true), [busy,setBusy]=useState(false), [optionsLoading,setOptionsLoading]=useState(false);
  const [selectedLocation,setSelectedLocation]=useState<Location|null>(null);
  const [copiedField,setCopiedField]=useState("");
  const [passwordUser,setPasswordUser]=useState<User|null>(null), [newPassword,setNewPassword]=useState(""), [passwordError,setPasswordError]=useState("");
  const [personId,setPersonId]=useState(""), [postId,setPostId]=useState(""), [nextUserId,setNextUserId]=useState(""), [password,setPassword]=useState(""), [confirmPassword,setConfirmPassword]=useState("");
  const [personOptions,setPersonOptions]=useState<DropdownOption<string>[]>([]), [postOptions,setPostOptions]=useState<DropdownOption<string>[]>([]);

  type TreeResponse={locations?:Location[];users?:User[];totalUsers?:number};
  const loadTree=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch("/api/users/tree",{cache:"no-store"});if(!response.ok)throw new Error(await apiMessage(response));const data=await response.json() as TreeResponse;const initialLocations=data.locations??[];setLocations(initialLocations);setUsers(data.users??[]);setTotalUsers(data.totalUsers??0);setLoaded(new Set(initialLocations.filter(item=>item.ParentId===null).map(item=>item.LocationId)));}catch(reason){setError(reason instanceof Error?reason.message:"دریافت اطلاعات انجام نشد.");}finally{setLoading(false);}},[]);
  useEffect(()=>{void loadTree();},[loadTree]);

  const loadNode=async(location:Location,force=false)=>{if(!force&&loaded.has(location.LocationId))return;setLoadingNodes(current=>new Set(current).add(location.LocationId));setError("");try{const params=new URLSearchParams({parentId:location.LocationId,parentType:location.LocationType});const response=await fetch(`/api/users/tree?${params}`,{cache:"no-store"});if(!response.ok)throw new Error(await apiMessage(response));const data=await response.json() as TreeResponse;setLocations(current=>{const map=new Map(current.map(item=>[item.LocationId,item]));(data.locations??[]).forEach(item=>map.set(item.LocationId,item));return [...map.values()];});setUsers(current=>[...current.filter(user=>user.LocationId!==location.LocationId),...(data.users??[])]);setTotalUsers(current=>data.totalUsers??current);setLoaded(current=>new Set(current).add(location.LocationId));}catch(reason){setError(reason instanceof Error?reason.message:"دریافت زیرمجموعه انجام نشد.");}finally{setLoadingNodes(current=>{const next=new Set(current);next.delete(location.LocationId);return next;});}};

  const query=search.trim().toLocaleLowerCase("fa");
  const visibleUsers=useMemo(()=>!query?users:users.filter(user=>`${user.FirstName} ${user.LastName} ${user.CodeMelli} ${user.OnvanPost}`.toLocaleLowerCase("fa").includes(query)),[query,users]);
  const childrenOf=(parentId:string|null)=>locations.filter(item=>item.ParentId===parentId&&item.LocationId!==parentId);
  const usersOf=(locationId:string)=>visibleUsers.filter(user=>user.LocationId===locationId);
  const toggle=async(location:Location)=>{const isOpen=expanded.has(location.LocationId);setExpanded(current=>{const next=new Set(current);isOpen?next.delete(location.LocationId):next.add(location.LocationId);return next;});if(!isOpen)await loadNode(location);};

  const openCreate=async(location:Location)=>{setSelectedLocation(location);setPersonId("");setPostId("");setNextUserId("");setPassword("");setConfirmPassword("");setFormError("");setPersonOptions([]);setPostOptions([]);setOptionsLoading(true);try{const response=await fetch(`/api/users/options?locationId=${encodeURIComponent(location.LocationId)}`,{cache:"no-store"});if(!response.ok)throw new Error(await apiMessage(response));const data=await response.json() as {persons?:{Value:string;Label:string;Description?:string}[];posts?:{Value:string;Label:string;Description?:string}[];nextUserId?:string};const mapOption=(item:{Value:string;Label:string;Description?:string})=>({value:String(item.Value),label:item.Label,description:item.Description});setPersonOptions((data.persons??[]).map(mapOption));setPostOptions((data.posts??[]).map(mapOption));setNextUserId(String(data.nextUserId??""));}catch(reason){setFormError(reason instanceof Error?reason.message:"دریافت گزینه‌ها انجام نشد.");}finally{setOptionsLoading(false);}};
  const closeModal=()=>{if(!busy)setSelectedLocation(null);};
  const saveUser=async()=>{if(!selectedLocation)return;if(!/^\d+$/.test(nextUserId)||Number(nextUserId)<1){setFormError("نام کاربر باید یک عدد مثبت باشد.");return;}if(!personId||!postId){setFormError("شخص و سمت را انتخاب کنید.");return;}if(password.length<5){setFormError("رمز اولیه باید حداقل ۵ کاراکتر باشد.");return;}if(password!==confirmPassword){setFormError("تکرار رمز با رمز اولیه یکسان نیست.");return;}setBusy(true);setFormError("");try{const response=await fetch("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:nextUserId,personId,postId,locationId:selectedLocation.LocationId,password})});if(!response.ok)throw new Error(await apiMessage(response));const location=selectedLocation;setSelectedLocation(null);setExpanded(current=>new Set(current).add(location.LocationId));await loadNode(location,true);}catch(reason){setFormError(reason instanceof Error?reason.message:"ثبت کاربر انجام نشد.");}finally{setBusy(false);}};
  const deleteUser=async(user:User)=>{if(!window.confirm(`حساب کاربری «${user.FirstName} ${user.LastName}» حذف شود؟`))return;setBusy(true);setError("");try{const response=await fetch(`/api/users?id=${encodeURIComponent(user.UserId)}`,{method:"DELETE"});if(!response.ok)throw new Error(await apiMessage(response));const location=locations.find(item=>item.LocationId===user.LocationId);if(location)await loadNode(location,true);else await loadTree();}catch(reason){setError(reason instanceof Error?reason.message:"حذف کاربر انجام نشد.");}finally{setBusy(false);}};
  const copyValue=async(value:string,key:string)=>{const text=latinDigits(value.trim());try{await navigator.clipboard.writeText(text);}catch{const area=document.createElement("textarea");area.value=text;area.style.position="fixed";area.style.opacity="0";document.body.appendChild(area);area.select();document.execCommand("copy");area.remove();}setCopiedField(key);window.setTimeout(()=>setCopiedField(current=>current===key?"":current),1400);};
  const openPasswordModal=(user:User)=>{setPasswordUser(user);setNewPassword("");setPasswordError("");};
  const closePasswordModal=()=>{if(!busy)setPasswordUser(null);};
  const changePassword=async()=>{if(!passwordUser)return;if(newPassword.length<5){setPasswordError("کلمه عبور باید حداقل ۵ کاراکتر باشد.");return;}setBusy(true);setPasswordError("");try{const response=await fetch("/api/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:passwordUser.UserId,password:newPassword})});if(!response.ok)throw new Error(await apiMessage(response));setPasswordUser(null);}catch(reason){setPasswordError(reason instanceof Error?reason.message:"تغییر کلمه عبور انجام نشد.");}finally{setBusy(false);}};

  const renderLocation=(location:Location,depth=0,path=new Set<string>()):ReactNode=>{if(path.has(location.LocationId))return null;const nextPath=new Set(path).add(location.LocationId);const children=childrenOf(location.LocationId).filter(child=>!nextPath.has(child.LocationId)),locationUsers=usersOf(location.LocationId),isOpen=query?true:expanded.has(location.LocationId),isNodeLoading=loadingNodes.has(location.LocationId);const tone=location.LocationType==="province"?styles.provinceTone:location.LocationType==="district"?styles.districtTone:location.LocationType==="county"?styles.countyTone:styles.headquartersTone;return <div className={styles.branch} key={`${depth}-${location.LocationId}`}>
    <div className={`${styles.locationLine} ${tone}`} style={{paddingRight:`${18+depth*24}px`}}><button className={styles.locationMain} onClick={()=>void toggle(location)}><span className={`${styles.chevron} ${isOpen?styles.open:""}`}><Icon kind="chevron"/></span><span className={styles.locationIcon}><Icon kind={location.LocationType==="headquarters"||location.LocationType==="province"?"building":"map"}/></span><strong>{location.LocationName}</strong><small>{isNodeLoading?"در حال دریافت...":loaded.has(location.LocationId)?`${locationUsers.length.toLocaleString("fa-IR")} کاربر`:"برای مشاهده کلیک کنید"}</small></button><button className={styles.addButton} onClick={()=>void openCreate(location)}><Icon kind="plus"/>افزودن کاربر</button></div>
    {isOpen&&<div className={styles.children}>{isNodeLoading&&<div className={styles.nodeLoading}>در حال دریافت زیرمجموعه...</div>}{locationUsers.map(user=>{const nationalKey=`national-${user.UserId}`,userKey=`user-${user.UserId}`;return <article className={styles.userRow} style={{marginRight:`${45+depth*24}px`}} key={user.UserId}><span className={styles.avatar}>{user.HasPhoto?<img src={`/api/persons/photo?id=${encodeURIComponent(user.PersonId)}`} alt=""/>:<Icon kind="user"/>}</span><div><strong>{user.FirstName} {user.LastName}</strong><span>{user.OnvanPost}</span></div><div className={styles.userCodes}><span className={styles.copyField}><i>کد ملی:</i><code>{user.CodeMelli}</code><button className={`${styles.copyButton} ${copiedField===nationalKey?styles.copied:""}`} onClick={()=>void copyValue(user.CodeMelli,nationalKey)} title={copiedField===nationalKey?"کپی شد":"کپی کد ملی"} aria-label="کپی کد ملی"><Icon kind={copiedField===nationalKey?"check":"copy"}/></button></span><span className={styles.copyField}><i>نام کاربر:</i><code>{user.UserId}</code><button className={`${styles.copyButton} ${copiedField===userKey?styles.copied:""}`} onClick={()=>void copyValue(user.UserId,userKey)} title={copiedField===userKey?"کپی شد":"کپی نام کاربر"} aria-label="کپی نام کاربر"><Icon kind={copiedField===userKey?"check":"copy"}/></button></span></div><span className={`${styles.status} ${user.IsActive?styles.active:styles.inactive}`}>{user.IsActive?"فعال":"غیرفعال"}</span><div className={styles.userActions}><button className={styles.resetButton} disabled={busy} onClick={()=>openPasswordModal(user)} title="تغییر کلمه عبور" aria-label="تغییر کلمه عبور"><Icon kind="key"/></button><button className={styles.deleteButton} disabled={busy} onClick={()=>void deleteUser(user)} title="حذف کاربر" aria-label="حذف کاربر"><Icon kind="trash"/></button></div></article>;})}{children.map(child=>renderLocation(child,depth+1,nextPath))}</div>}
  </div>;};

  return <main className={styles.page}><section className={styles.heading}><div><span>کاربران و دسترسی‌ها</span><h2>فهرست درختی کاربران</h2></div><div className={styles.total}><strong>{totalUsers.toLocaleString("fa-IR")}</strong><span>کاربر ثبت‌شده</span></div></section><section className={styles.card}><label className={styles.search}><Icon kind="search"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="جستجو در کاربران بارگذاری‌شده..."/></label>{loading?<div className={styles.message}>در حال دریافت ستاد و استان‌ها...</div>:<>{error&&<div className={`${styles.message} ${styles.error}`}>{error}</div>}<div className={styles.tree}>{childrenOf(null).map(root=>renderLocation(root))}</div></>}</section>
  {selectedLocation&&<div className={styles.backdrop} onMouseDown={closeModal}><section className={styles.modal} onMouseDown={event=>event.stopPropagation()}><button className={styles.closeButton} onClick={closeModal}><Icon kind="close"/></button><header><span><Icon kind="user"/></span><div><h3>افزودن کاربر</h3><p>{selectedLocation.LocationName}</p></div></header>{formError&&<div className={styles.formError}>{formError}</div>}<div className={styles.formGrid}><label><span>شخص <b>*</b></span><SearchableDropdown value={personId} options={personOptions} onChange={setPersonId} searchPlaceholder="جستجوی نام یا کد ملی..." noResultText={optionsLoading?"در حال دریافت...":"شخص قابل انتخابی وجود ندارد."} ariaLabel="انتخاب شخص" menuWidth={430}/></label><label><span>سمت <b>*</b></span><SearchableDropdown value={postId} options={postOptions} onChange={setPostId} searchPlaceholder="جستجوی سمت..." noResultText={optionsLoading?"در حال دریافت...":"سمتی برای این محل تعریف نشده است."} ariaLabel="انتخاب سمت" menuWidth={430}/></label><label><span>نام کاربر (UserId) <b>*</b></span><input className={styles.generatedInput} type="text" inputMode="numeric" value={nextUserId} placeholder={optionsLoading?"در حال محاسبه...":""} onChange={event=>setNextUserId(event.target.value.replace(/\D/g,""))}/></label><label><span className={styles.passwordLabel}>رمز اولیه <b>*</b><button type="button" onClick={()=>{setPassword("123456789");setConfirmPassword("123456789");}}>123456789</button></span><input type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete="new-password"/></label><label><span>تکرار رمز <b>*</b></span><input type="password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} autoComplete="new-password"/></label></div><footer><button className={styles.cancelButton} onClick={closeModal}>انصراف</button><button className={styles.saveButton} disabled={busy||optionsLoading} onClick={()=>void saveUser()}>{busy?"در حال ثبت...":"ثبت کاربر"}</button></footer></section></div>}
  {passwordUser&&<div className={styles.backdrop} onMouseDown={closePasswordModal}><section className={`${styles.modal} ${styles.passwordModal}`} onMouseDown={event=>event.stopPropagation()}><button className={styles.closeButton} onClick={closePasswordModal}><Icon kind="close"/></button><header><span><Icon kind="key"/></span><div><h3>تغییر کلمه عبور</h3><p>{passwordUser.FirstName} {passwordUser.LastName} — نام کاربر: {passwordUser.UserId}</p></div></header>{passwordError&&<div className={styles.formError}>{passwordError}</div>}<div className={styles.formGrid}><label className={styles.fullField}><span>کلمه عبور جدید <b>*</b></span><input type="password" value={newPassword} onChange={event=>setNewPassword(event.target.value)} autoComplete="new-password" autoFocus onKeyDown={event=>{if(event.key==="Enter")void changePassword();}}/></label></div><footer><button className={styles.cancelButton} onClick={closePasswordModal}>انصراف</button><button className={styles.saveButton} disabled={busy} onClick={()=>void changePassword()}>{busy?"در حال ثبت...":"ثبت کلمه عبور"}</button></footer></section></div>}
  </main>;
}
