"use client";

import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { SearchableDropdown, type DropdownOption } from "../Dropdown";
import styles from "./ElectionCandidates.module.css";

type ElectionPeriod = { CodeEntekhabat:string; OnvanDore:string; VazeyatDore:number|null; ShomarehDore:number|null; ShomarehMarhale:number|null; TarikhEntekhabat:string|null; IsDefault:number|null };
type Location = { LocationId:string; ParentId:string|null; ProvinceId:string|null; LocationName:string; LocationType:"headquarters"|"province"|"district" };
type Candidate = { ShomarehParvandeh:string; CodeMelli:string; FirstName:string; LastName:string; NamePedar:string|null; TarikhTavalod:string|null; TelHamrah:string|null; Jensiyat:number|null; Taahol:number|null; IsLife:number|null; IsRohani:number|null; Ostan:number|null; NameOstan:string|null; CodeHozeh:number|null; NameHozeh:string|null; Natije:number|null; Natije_NameFarsi:string|null };
type IconName = "tree"|"building"|"map"|"chevron"|"search"|"user"|"arrow"|"folder"|"more";

function Icon({name,size=18}:{name:IconName;size?:number}){const paths:Record<IconName,ReactNode>={
  tree:<><path d="M12 3v6M6 21v-5h12v5M6 16v-3h12v3M12 9H6v4M12 9h6v4"/><circle cx="12" cy="3" r="2"/><circle cx="6" cy="21" r="2"/><circle cx="18" cy="21" r="2"/></>,
  building:<><path d="M4 21V4h12v17M16 9h4v12M8 8h4M8 12h4M8 16h4M2 21h20"/></>,
  map:<><path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3Z"/><path d="M9 3v15M15 6v15"/></>,
  chevron:<path d="m9 18 6-6-6-6"/>,search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
  user:<><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></>,arrow:<path d="m9 18 6-6-6-6"/>,folder:<><path d="M3 6h7l2 2h9v11H3Z"/></>,more:<><circle cx="12" cy="5" r="1.25" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1.25" fill="currentColor" stroke="none"/><circle cx="12" cy="19" r="1.25" fill="currentColor" stroke="none"/></>
};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}

async function responseMessage(response:Response){try{return ((await response.json()) as {message?:string}).message||"عملیات انجام نشد."}catch{return "عملیات انجام نشد."}}
const locationKey=(location:Location)=>`${location.LocationType}:${location.ProvinceId??"0"}:${location.LocationId}`;

export default function ElectionCandidates(){
  const [periods,setPeriods]=useState<ElectionPeriod[]>([]),[electionId,setElectionId]=useState("");
  const [locations,setLocations]=useState<Location[]>([]),[selected,setSelected]=useState<Location|null>(null);
  const [expanded,setExpanded]=useState<Set<string>>(new Set()),[loadedProvinces,setLoadedProvinces]=useState<Set<string>>(new Set()),[loadingProvinces,setLoadingProvinces]=useState<Set<string>>(new Set());
  const [items,setItems]=useState<Candidate[]>([]),[totalCount,setTotalCount]=useState(0),[page,setPage]=useState(1);
  const [search,setSearch]=useState(""),[initialLoading,setInitialLoading]=useState(true),[listLoading,setListLoading]=useState(false),[error,setError]=useState("");
  const pageSize=15,pageCount=Math.max(1,Math.ceil(totalCount/pageSize));

  useEffect(()=>{let active=true;const load=async()=>{setInitialLoading(true);setError("");try{const response=await fetch("/api/candidates/periods",{cache:"no-store"});if(!response.ok)throw new Error(await responseMessage(response));const data=await response.json() as {items?:ElectionPeriod[]};const rows=data.items??[];if(!active)return;const defaultPeriod=rows.find(period=>Number(period.IsDefault)===1)??rows[0];setPeriods(rows);setElectionId(defaultPeriod?.CodeEntekhabat??"");}catch(reason){if(active)setError(reason instanceof Error?reason.message:"دریافت دوره‌ها انجام نشد.");}finally{if(active)setInitialLoading(false);}};void load();return()=>{active=false};},[]);

  const loadRoot=useCallback(async()=>{if(!electionId)return;setInitialLoading(true);setError("");setLocations([]);setSelected(null);setExpanded(new Set());setLoadedProvinces(new Set());try{const response=await fetch(`/api/candidates/tree?electionId=${encodeURIComponent(electionId)}`,{cache:"no-store"});if(!response.ok)throw new Error(await responseMessage(response));const data=await response.json() as {locations?:Location[]};const rows=data.locations??[];setLocations(rows);const first=rows.find(item=>item.LocationType==="headquarters")??rows[0]??null;setSelected(first);if(first?.LocationType==="headquarters")setExpanded(new Set([locationKey(first)]));setPage(1);}catch(reason){setError(reason instanceof Error?reason.message:"دریافت ساختار محل‌ها انجام نشد.");}finally{setInitialLoading(false);}},[electionId]);
  useEffect(()=>{void loadRoot();},[loadRoot]);

  const loadDistricts=async(province:Location)=>{if(loadedProvinces.has(province.LocationId)||loadingProvinces.has(province.LocationId))return;setLoadingProvinces(current=>new Set(current).add(province.LocationId));try{const response=await fetch(`/api/candidates/tree?electionId=${encodeURIComponent(electionId)}&provinceId=${encodeURIComponent(province.LocationId)}`,{cache:"no-store"});if(!response.ok)throw new Error(await responseMessage(response));const data=await response.json() as {locations?:Location[]};setLocations(current=>{const map=new Map(current.map(item=>[locationKey(item),item]));(data.locations??[]).forEach(item=>map.set(locationKey(item),item));return [...map.values()]});setLoadedProvinces(current=>new Set(current).add(province.LocationId));}catch(reason){setError(reason instanceof Error?reason.message:"دریافت حوزه‌های انتخابیه انجام نشد.");}finally{setLoadingProvinces(current=>{const next=new Set(current);next.delete(province.LocationId);return next;});}};

  const chooseLocation=async(location:Location)=>{setSelected(location);setPage(1);const key=locationKey(location);if(location.LocationType!=="district"){const isOpen=expanded.has(key);setExpanded(current=>{const next=new Set(current);isOpen?next.delete(key):next.add(key);return next;});if(location.LocationType==="province"&&!isOpen)await loadDistricts(location);}};

  const loadCandidates=useCallback(async()=>{if(!electionId||!selected)return;setListLoading(true);setError("");const params=new URLSearchParams({electionId,locationType:selected.LocationType,locationId:selected.LocationId,page:String(page),pageSize:String(pageSize)});if(selected.ProvinceId)params.set("provinceId",selected.ProvinceId);if(search.trim())params.set("search",search.trim());try{const response=await fetch(`/api/candidates?${params}`,{cache:"no-store"});if(!response.ok)throw new Error(await responseMessage(response));const data=await response.json() as {items?:Candidate[];totalCount?:string};setItems(data.items??[]);setTotalCount(Number(data.totalCount??0));}catch(reason){setItems([]);setTotalCount(0);setError(reason instanceof Error?reason.message:"دریافت داوطلبان انجام نشد.");}finally{setListLoading(false);}},[electionId,page,search,selected]);
  useEffect(()=>{const timer=window.setTimeout(()=>void loadCandidates(),250);return()=>window.clearTimeout(timer);},[loadCandidates]);

  const periodOptions=useMemo<DropdownOption<string>[]>(()=>periods.map(period=>({value:String(period.CodeEntekhabat),label:period.OnvanDore,description:[period.ShomarehDore?`دوره ${period.ShomarehDore}`:"",period.TarikhEntekhabat??""].filter(Boolean).join(" — ")})),[periods]);
  const childrenOf=(parentId:string|null)=>locations.filter(item=>item.ParentId===parentId);
  const rootLocations=locations.filter(item=>item.ParentId===null);
  const renderLocation=(location:Location,depth=0):ReactNode=>{const key=locationKey(location),isOpen=expanded.has(key),isSelected=selected?locationKey(selected)===key:false,isLoading=loadingProvinces.has(location.LocationId);const children=childrenOf(location.LocationId);return <div className={styles.branch} key={key}><button className={`${styles.location} ${styles[location.LocationType]} ${isSelected?styles.selected:""}`} style={{paddingRight:`${10+depth*14}px`}} onClick={()=>void chooseLocation(location)}><span className={`${styles.chevron} ${isOpen?styles.open:""} ${location.LocationType==="district"?styles.hidden:""}`}><Icon name="chevron" size={14}/></span><span className={styles.locationIcon}><Icon name={location.LocationType==="headquarters"?"building":location.LocationType==="province"?"map":"folder"} size={17}/></span><span>{location.LocationName}</span>{isLoading&&<small>...</small>}</button>{isOpen&&children.length>0&&<div>{children.map(child=>renderLocation(child,depth+1))}</div>}</div>};
  const selectedPeriod=periods.find(period=>String(period.CodeEntekhabat)===electionId);

  return <main className={styles.page}>
    <section className={styles.pageBar}><div><span>داوطلبان انتخابات</span><h2>اشخاص</h2></div><div className={styles.periodPicker}><label>دوره انتخابات</label><SearchableDropdown compact value={electionId} options={periodOptions} onChange={value=>{setElectionId(value);setSearch("");setPage(1);}} placeholder={initialLoading?"در حال دریافت...":"انتخاب دوره انتخابات"} searchPlaceholder="جستجوی دوره..." noResultText="دوره‌ای ثبت نشده است." ariaLabel="انتخاب دوره انتخابات" menuWidth={390}/></div></section>
    <section className={styles.layout}>
      <aside className={styles.treeCard}><header><span><Icon name="tree"/></span><div><h3>ساختار محل‌ها</h3><p>{selectedPeriod?.OnvanDore??"دوره انتخاب نشده"}</p></div></header><div className={styles.tree}>{initialLoading?<div className={styles.treeMessage}>در حال دریافت ستاد و استان‌ها...</div>:rootLocations.length?rootLocations.map(item=>renderLocation(item)):<div className={styles.treeMessage}>محلی برای نمایش وجود ندارد.</div>}</div></aside>
      <section className={styles.listCard}><header className={styles.listHeader}><div><span>{selected?.LocationType==="headquarters"?"کل کشور":selected?.LocationType==="province"?"استان":"حوزه انتخابیه"}</span><h3>{selected?.LocationName??"انتخاب محل"}</h3></div><div className={styles.headerActions}><label className={styles.search}><Icon name="search"/><input value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}} placeholder="جستجو با نام، نام خانوادگی، کد ملی یا شماره پرونده..."/></label><span className={styles.count}>{totalCount.toLocaleString("fa-IR")} داوطلب</span></div></header>{error&&<div className={styles.error}>{error}</div>}<div className={styles.tableWrap}><table><thead><tr><th>ردیف</th><th>داوطلب</th><th>کد ملی</th><th>شماره پرونده</th><th>نام پدر</th><th>تاریخ تولد</th><th>استان / حوزه</th><th>نتیجه</th></tr></thead><tbody>{listLoading?<tr><td colSpan={8} className={styles.empty}>در حال دریافت داوطلبان...</td></tr>:items.map((item,index)=><tr key={item.ShomarehParvandeh}><td className={styles.rowNumber}>{((page-1)*pageSize+index+1).toLocaleString("fa-IR")}</td><td><span className={styles.personCell}><span className={styles.person}><i><Icon name="user" size={16}/></i><span>{item.FirstName} {item.LastName}<small>{item.TelHamrah||"شماره همراه ثبت نشده"}</small></span></span><span className={styles.candidateMenu}><button type="button" className={styles.candidateMenuButton} aria-label={`عملیات ${item.FirstName} ${item.LastName}`} aria-haspopup="menu"><Icon name="more" size={18}/></button><span className={styles.candidateMenuList} role="menu"><button type="button" role="menuitem">اطلاعات فردی</button><button type="button" role="menuitem">صلاحیت فردی</button><button type="button" role="menuitem">تولید کاربرگ تحقیق</button></span></span></span></td><td className={styles.ltr}>{item.CodeMelli}</td><td className={styles.ltr}>{item.ShomarehParvandeh}</td><td>{item.NamePedar||"—"}</td><td className={styles.ltr}>{item.TarikhTavalod||"—"}</td><td><span className={styles.place}>{item.NameOstan||"—"}<small>{item.NameHozeh||"حوزه ثبت نشده"}</small></span></td><td><span className={styles.result}>{item.Natije_NameFarsi||"ثبت نشده"}</span></td></tr>)}{!listLoading&&items.length===0&&<tr><td colSpan={8} className={styles.empty}>برای محل و دوره انتخاب‌شده داوطلبی وجود ندارد.</td></tr>}</tbody></table></div><footer><span>صفحه {page.toLocaleString("fa-IR")} از {pageCount.toLocaleString("fa-IR")}</span><div><button disabled={page<=1||listLoading} onClick={()=>setPage(current=>Math.max(1,current-1))}><Icon name="arrow" size={14}/></button><span>{page.toLocaleString("fa-IR")}</span><button className={styles.next} disabled={page>=pageCount||listLoading} onClick={()=>setPage(current=>Math.min(pageCount,current+1))}><Icon name="arrow" size={14}/></button></div></footer></section>
    </section>
  </main>;
}
